### ISSUE TITLE
Erro while trying to login

### ISSUE THREAD

**Issue by brenoc** [vtex/toolbelt#1]
When I type `vtex login` or any other command, except `help`, I get:

```sh
$ vtex login
module.js:340
    throw err;
          ^
Error: Cannot find module 'Q'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/breno/local/lib/node_modules/vtex/lib/lib/auth.js:9:7)
    at Object.<anonymous> (/home/breno/local/lib/node_modules/vtex/lib/lib/auth.js:225:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by brenoc** [comment]
This might be useful, the log of my install:

```sh
npm WARN optional dep failed, continuing fsevents@0.3.5
/home/breno/local/bin/vtex-publish -> /home/breno/local/lib/node_modules/vtex/lib/vtex-publish.js
/home/breno/local/bin/vtex -> /home/breno/local/lib/node_modules/vtex/lib/vtex.js
/home/breno/local/bin/vtex-login -> /home/breno/local/lib/node_modules/vtex/lib/vtex-login.js
/home/breno/local/bin/vtex-logout -> /home/breno/local/lib/node_modules/vtex/lib/vtex-logout.js
/home/breno/local/bin/vtex-watch -> /home/breno/local/lib/node_modules/vtex/lib/vtex-watch.js
npm WARN unmet dependency /home/breno/local/lib/node_modules/karma-requirejs/node_modules/grunt-karma/node_modules/karma/node_modules/http-proxy requires colors@'0.x.x' but will load
npm WARN unmet dependency /home/breno/local/lib/node_modules/karma-requirejs/node_modules/grunt-karma/node_modules/karma/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
vtex@0.1.1 /home/breno/local/lib/node_modules/vtex
├── q@1.2.0
├── semver@4.3.1
├── shelljs@0.3.0
├── commander@2.7.1 (graceful-readlink@1.0.1)
├── chokidar@1.0.0-rc4 (async-each@0.1.6, is-binary-path@1.0.0, glob-parent@1.2.0, anymatch@1.1.0, readdirp@1.3.0)
├── glob@5.0.3 (inherits@2.0.1, inflight@1.0.4, once@1.3.1, minimatch@2.0.4)
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.3.3, form-data@0.2.0, combined-stream@0.0.7, mime-types@2.0.10, bl@0.9.4, http-signature@0.10.1, tough-cookie@0.12.1, hawk@2.3.1)
├── archiver@0.14.3 (buffer-crc32@0.2.5, lazystream@0.1.0, async@0.9.0, readable-stream@1.0.33, tar-stream@1.1.2, glob@4.3.5, lodash@3.2.0, zip-stream@0.5.1)
└── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.5, winston@0.8.3, utile@0.2.1)
```
