### ISSUE TITLE
Install error not handled in v3

### ISSUE THREAD

**Issue by klzns** [vtex/toolbelt#1077]
## Expected Behavior
To give a proper error message.

## Current Behavior

![image](https://user-images.githubusercontent.com/284515/114874936-30f5af80-9dd3-11eb-8903-bc54e5592622.png)
```sh
10:12:45.175 - error: Unhandled exception
10:12:45.175 - error: Please report the issue in https://github.com/vtex/toolbelt/issues
10:12:45.176 - error: Raw error: InstallStatus is not defined ReferenceError: InstallStatus is not defined
    at prepareInstall (/usr/local/Cellar/vtex/2.125.1/lib/client/3.5.1-beta.2209ba6a/lib/modules/apps/install.js:110:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Install.run (/usr/local/Cellar/vtex/2.125.1/lib/client/3.5.1-beta.2209ba6a/lib/commands/install.js:12:9)
    at async Install._run (/usr/local/Cellar/vtex/2.125.1/lib/client/3.5.1-beta.2209ba6a/lib/api/oclif/CustomCommand.js:27:28)
    at async Config.ctx.config.runCommand (/usr/local/Cellar/vtex/2.125.1/lib/client/3.5.1-beta.2209ba6a/node_modules/@tiagonapoli/oclif-plugin-spaced-commands/lib/hooks/init.js:89:9)
    at async Main.run (/usr/local/Cellar/vtex/2.125.1/lib/client/3.5.1-beta.2209ba6a/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/usr/local/Cellar/vtex/2.125.1/lib/client/3.5.1-beta.2209ba6a/node_modules/@oclif/command/lib/command.js:43:20)
10:12:45.177 - error: ErrorID: 50ba848970256cce82d10aaf0443c917
```

## Steps to Reproduce (for bugs)
1. Try to install the app vtex.shareasale (I might fix the app error, so it might disappear)

## Your Environment

10:12:38.277 - debug: Toolbelt version: 3.5.1-beta.2209ba6a
10:12:38.281 - debug: node v12.12.0 - darwin 20.3.0

**Comment by gris** [comment]
Hey, @klzns, thanks for submitting this issue. It is already fixed in 3.5.2-beta. https://github.com/vtex/toolbelt/pull/1067 can you update it and try again?

**Comment by klzns** [comment]
When I run `vtex autoupdate` it is downgrading:

![image](https://user-images.githubusercontent.com/284515/114877272-8206a300-9dd5-11eb-97c1-582fc37c0159.png)

🤔

**Comment by gris** [comment]
It seems correct to me. 3.6.0-beta is the latest beta version.

**Comment by klzns** [comment]
Oh, I thought it should go up to 3.5.2-beta

**Comment by gris** [comment]
https://github.com/vtex/toolbelt/pull/1072 there was a new release aftet this one :D
