### ISSUE TITLE
Problems with the `vtex workspace list` command

### ISSUE THREAD

**Issue by victorshp** [vtex/toolbelt#1140]
All other VTEX CLI commands are functioning adequately, but the `vtex workspace list` command shows an error. I am usng vtex version 3.0.0 (vtex/3.0.0 linux-x64 node-v12.22.1).

Here is the output:
```
$ vtex workspace list
15:35:56.117 - error: Unhandled exception  
15:35:56.122 - error: Please report the issue in https://github.com/vtex/toolbelt/issues  
15:35:56.124 - error: Raw error: stripped.split is not a function TypeError: stripped.split is not a function
    at Object.exports.strlen (/home/victorshp/.config/yarn/global/node_modules/cli-table/lib/utils.js:85:24)
    at get_width (/home/victorshp/.config/yarn/global/node_modules/cli-table/lib/index.js:138:70)
    at /home/victorshp/.config/yarn/global/node_modules/cli-table/lib/index.js:131:68
    at Array.forEach (<anonymous>)
    at extractColumnWidths (/home/victorshp/.config/yarn/global/node_modules/cli-table/lib/index.js:130:9)
    at /home/victorshp/.config/yarn/global/node_modules/cli-table/lib/index.js:104:11
    at Array.forEach (<anonymous>)
    at Table.toString (/home/victorshp/.config/yarn/global/node_modules/cli-table/lib/index.js:101:16)
    at /home/victorshp/.config/yarn/global/node_modules/@vtex/cli-plugin-workspace/build/modules/list.js:19:39
```

**Comment by alexminza** [comment]
```
$ vtex workspace list
11:16:21.343 - error: Unhandled exception  
11:16:21.344 - error: Please report the issue in https://github.com/vtex/toolbelt/issues  
11:16:21.345 - error: Raw error: stripped.split is not a function TypeError: stripped.split is not a function
    at Object.exports.strlen (/Users/Alexander/.config/yarn/global/node_modules/cli-table/lib/utils.js:85:24)
    at get_width (/Users/Alexander/.config/yarn/global/node_modules/cli-table/lib/index.js:138:70)
    at /Users/Alexander/.config/yarn/global/node_modules/cli-table/lib/index.js:131:68
    at Array.forEach (<anonymous>)
    at extractColumnWidths (/Users/Alexander/.config/yarn/global/node_modules/cli-table/lib/index.js:130:9)
    at /Users/Alexander/.config/yarn/global/node_modules/cli-table/lib/index.js:104:11
    at Array.forEach (<anonymous>)
    at Table.toString (/Users/Alexander/.config/yarn/global/node_modules/cli-table/lib/index.js:101:16)
    at /Users/Alexander/.config/yarn/global/node_modules/@vtex/cli-plugin-workspace/build/modules/list.js:19:39
    at processTicksAndRejections (node:internal/process/task_queues:96:5)  
11:16:21.350 - error: ErrorID: e8510c483587f13210ca7bbf198bddb7  
```

**Comment by alexminza** [comment]
Related issue: https://github.com/vtex/toolbelt/issues/1147
