### ISSUE TITLE
Failed to run yarn in react  

### ISSUE THREAD

**Issue by raphaelfelixs2holding** [vtex/toolbelt#1232]
PS C:\D\BitBucket\Vtex IO\Cantao\2024\app-global-css> vtex link
17:06:26.181 - info: Running yarn in react  
➤ YN0050: The --ignore-engines option is deprecated; engine checking isn't a core feature anymore
17:06:27.514 - error: Failed to run yarn in react  
17:06:27.517 - error: Unhandled exception  
17:06:27.518 - error: Please report the issue in https://github.com/vtex/toolbelt/issues  
17:06:27.519 - error: Raw error: Command failed: "C:\Program Files\vtex\client\node_modules\yarn\bin\yarn" --non-interactive --ignore-engines Error: Command failed: "C:\Program Files\vtex\client\node_modules\yarn\bin\yarn" --non-interactive --ignore-engines
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at ChildProcess.execSync (C:\Program Files\vtex\client\node_modules\child-process-es6-promise\index.js:232:40)
    at Object.exports.runYarn (C:\Program Files\vtex\client\lib\modules\utils.js:22:33)
    at exports.runYarnIfPathExists (C:\Program Files\vtex\client\lib\modules\utils.js:30:21)
    at _map (C:\Program Files\vtex\client\node_modules\ramda\src\internal\_map.js:6:19)
    at map (C:\Program Files\vtex\client\node_modules\ramda\src\map.js:64:14)
    at C:\Program Files\vtex\client\node_modules\ramda\src\internal\_dispatchable.js:41:15
    at Object.f2 [as map] (C:\Program Files\vtex\client\node_modules\ramda\src\internal\_curry2.js:29:14)
    at Object.appLink (C:\Program Files\vtex\client\lib\modules\apps\link.js:232:13)
    at async Link.run (C:\Program Files\vtex\client\lib\commands\link.js:11:9)
    at async Link._run (C:\Program Files\vtex\client\lib\api\oclif\CustomCommand.js:27:28)
    at async Config.ctx.config.runCommand (C:\Program Files\vtex\client\node_modules\@tiagonapoli\oclif-plugin-spaced-commands\lib\hooks\init.js:89:9)
    at async Main.run (C:\Program Files\vtex\client\node_modules\@oclif\command\lib\main.js:27:9)
    at async Main._run (C:\Program Files\vtex\client\node_modules\@oclif\command\lib\command.js:43:20) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 24212,
  stdout: null,
  stderr: null
}
17:06:27.526 - error: ErrorID: f2fbf4cb623d7934b312cf6a215b063f

**Comment by marcollahc** [comment]
Check the yarn version with command in your shell:

`yarn -v`

If the version >= 3, try use this command:

`yarn set version classic`

Yesterday I had the same problem and this command helps me a lot. I hope it helps you too.

I don't know what changed, but I couldn't solve it without this command.

Docs: https://yarnpkg.com/cli/set/version
