### ISSUE TITLE
Erro ao tentar utilizar o comando vtex link

### ISSUE THREAD

**Issue by raphaelburiti** [vtex/toolbelt#1234]
## Current Behavior

<img width="909" alt="image" src="https://github.com/user-attachments/assets/a74258e4-e343-43bc-8840-9deb590c59bd">

`19:35:03.118 - error: Failed to run yarn in node  
19:35:03.121 - error: Unhandled exception  
19:35:03.122 - error: Please report the issue in https://github.com/vtex/toolbelt/issues  
19:35:03.123 - error: Raw error: Command failed: "/opt/homebrew/Cellar/vtex/4.1.0/libexec/node_modules/yarn/bin/yarn" --non-interactive --ignore-engines Error: Command failed: "/opt/homebrew/Cellar/vtex/4.1.0/libexec/node_modules/yarn/bin/yarn" --non-interactive --ignore-engines
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at ChildProcess.execSync (/opt/homebrew/Cellar/vtex/4.1.0/libexec/node_modules/child-process-es6-promise/index.js:232:40)
    at exports.runYarn (/opt/homebrew/Cellar/vtex/4.1.0/libexec/lib/modules/utils.js:22:33)
    at exports.runYarnIfPathExists (/opt/homebrew/Cellar/vtex/4.1.0/libexec/lib/modules/utils.js:30:21)
    at _map (/opt/homebrew/Cellar/vtex/4.1.0/libexec/node_modules/ramda/src/internal/_map.js:6:19)
    at map (/opt/homebrew/Cellar/vtex/4.1.0/libexec/node_modules/ramda/src/map.js:64:14)
    at /opt/homebrew/Cellar/vtex/4.1.0/libexec/node_modules/ramda/src/internal/_dispatchable.js:41:15
    at Object.f2 [as map] (/opt/homebrew/Cellar/vtex/4.1.0/libexec/node_modules/ramda/src/internal/_curry2.js:29:14)
    at Object.appLink (/opt/homebrew/Cellar/vtex/4.1.0/libexec/lib/modules/apps/link.js:221:13)
    at async Link.run (/opt/homebrew/Cellar/vtex/4.1.0/libexec/lib/commands/link.js:11:9)
    at async Link._run (/opt/homebrew/Cellar/vtex/4.1.0/libexec/lib/api/oclif/CustomCommand.js:27:28)
    at async ctx.config.runCommand (/opt/homebrew/Cellar/vtex/4.1.0/libexec/node_modules/@tiagonapoli/oclif-plugin-spaced-commands/lib/hooks/init.js:89:9)
    at async Main.run (/opt/homebrew/Cellar/vtex/4.1.0/libexec/node_modules/@oclif/command/lib/main.js:27:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 82285,
  stdout: null,
  stderr: null
}  
19:35:03.129 - error: ErrorID: e59528bffb079d7a99013fa2572087ed  `

## Steps to Reproduce (for bugs)
1. acessar o diretorio com um app vtex io
2. rodar o comando vtex link

## Your Environment
* Version used: vtex/4.1.0 darwin-x64 node-v20.16.0
* macOS 14.5 BuildVersion: 23F79 kernel: 23.5.0

**Comment by VictorAlmaraz** [comment]
Same here, did you manage how to fix it?

**Comment by marcollahc** [comment]
I changed the yarn version is the problem resolved. 

Check if this solution works with you too: https://github.com/vtex/toolbelt/issues/1232
