### ISSUE TITLE
ERROR AL HACER VTEX LOGIN

### ISSUE THREAD

**Issue by webmastertvn** [vtex/toolbelt#1238]
AL realizar el vtex login desde mi store local, me genera un error que no pasaba. Me pide el nombre de la cuenta, se la agrego y me sigue arrojando error para conectar al master. Quiero crear un ticket, no quiero hacer la consulta por copiloto, porque ya he hecho el proceso varias veces. Este es el error:√ Account: · tvnovedadestv
15:00:32.657 - error: Unhandled exception
15:00:32.658 - error: Please report the issue in https://github.com/vtex/toolbelt/issues
15:00:32.659 - error: Raw error: Error trying to call client before login. Error: Error trying to call client before login.
at C:\Users\DAYSI.LOPEZ\AppData\Local\Yarn\Data\global\node_modules\vtex\lib\api\clients\IOClients\IOClientFactory.js:54:27
at exports.default (C:\Users\DAYSI.LOPEZ\AppData\Local\Yarn\Data\global\node_modules\vtex\lib\modules\apps\list.js:31:28)
at List.run (C:\Users\DAYSI.LOPEZ\AppData\Local\Yarn\Data\global\node_modules\vtex\lib\commands\list.js:10:29)
at List._run (C:\Users\DAYSI.LOPEZ\AppData\Local\Yarn\Data\global\node_modules\vtex\lib\api\oclif\CustomCommand.js:27:39)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
15:00:32.664 - error: ErrorID: 1a12eb596819913a73b531eb4cfbdadf

![error-vtex-login](https://github.com/user-attachments/assets/4ae00aad-fed6-4b58-b43d-d0588a63c3e6)
![error-vtex-login-2](https://github.com/user-attachments/assets/f427b3f5-7e69-4636-acd2-efb64045d18d)
![error-paso-1](https://github.com/user-attachments/assets/b4b2a867-e644-41f3-b035-c6441968296d)

**Comment by Aurorahey** [comment]
Same issue

**Comment by TheoOliveira** [comment]
installing from the curl getting not the same issue because i cant see any way to verbose out the command spits but is stuck to the login doesnt open the browser

**Comment by TheoOliveira** [comment]
Could clarify that? You mean the computer has it or the company that is set
to use vtex

Em qui., 20 de fev. de 2025 09:13, Daniel S. Silva ***@***.***>
escreveu:

**Comment by TheoOliveira** [comment]
Because if its the case, that's not the case for me.

Em qui., 20 de fev. de 2025 09:13, Daniel S. Silva ***@***.***>
escreveu:

**Comment by odanielsantana** [comment]
> Could clarify that? You mean the computer has it or the company that is set to use vtex

Hi @TheoOliveira , 
I mean that if your PC is using a VPN or Proxy, that could be causing the issue.

You can try this: add the following line to your `.bashrc` file:

```export NODE_TLS_REJECT_UNAUTHORIZED=0```

After that, try running the login command in your CLI. 
Even if it works, you might still encounter some issues while running the project.
