### ISSUE TITLE
Watch retorna "null"

### ISSUE THREAD

**Issue by josantana** [vtex/toolbelt#65]
![screenshot 2015-10-28 16 43 11](https://cloud.githubusercontent.com/assets/5032844/10799327/66d1e260-7d93-11e5-8c77-850b73c52c5a.png)

**Comment by brenoc** [comment]
Pode dar `vtex -v`?

**Comment by josantana** [comment]
v0.10.1

**Comment by brenoc** [comment]
Poderia tentar:
```
npm install
vtex logout
vtex login
```

**Comment by josantana** [comment]
Feito. Mas não resolveu, @brenoc. Tentei remover os pacotes extra que instalei por conta do Sass, pra ver se não era algum conflito, mas continua retornando `null`.

Caso interesse, meu *package.json* tem estas dependências:

```
"dependencies": {
    "colr": "^1.2.2",
    "lodash-compat": "^3.10.1",
    "react-colorpicker": "^0.3.14",
    "react-dragula": "^1.0.12"
},
"devDependencies": {
    "babel-core": "^5.4.7",
    "babel-eslint": "^3.1.20",
    "babel-loader": "^5.2.0",
    "babel-plugin-react-transform": "^1.1.1",
    "bootstrap": "^3.3.4",
    "css-loader": "^0.9.1",
    "eslint": "^1.3.1",
    "eslint-config-vtex": "^1.0.0",
    "eslint-loader": "^1.0.0",
    "eslint-plugin-react": "^3.5.1",
    "express": "^4.13.3",
    "file-loader": "^0.8.1",
    "http-proxy": "^1.11.2",
    "less": "^2.4.0",
    "less-loader": "^2.2.0",
    "loader-utils": "^0.2.6",
    "minimist": "^1.1.1",
    "node-sass": "^3.4.0",
    "raw-loader": "^0.5.1",
    "react": "^0.14.0",
    "react-proxy-loader": "^0.3.4",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.0",
    "redbox-react": "^1.0.1",
    "sass-loader": "^3.1.0",
    "style-loader": "^0.9.0",
    "svgo": "^0.5.5",
    "svgo-loader": "^1.1.0",
    "url-loader": "^0.5.5",
    "webpack": "^1.12.2",
    "webpack-hot-middleware": "^2.0.0"
}
```

**Comment by brenoc** [comment]
Pode ver qual a versão do node e do npm?
```
node -v
npm -v
```

**Comment by josantana** [comment]
Node: `v2.5.0`
NPM: `2.13.2`

**Comment by brenoc** [comment]
@josantana Qual OS vc usa? Vou te passar instruções pra atualizar o node e o npm.

**Comment by josantana** [comment]
Mac

**Comment by josantana** [comment]
Jurei que agora ia dar certo. Realmente, estava com uma versão muito antiga do node na máquina. Estava com tudo atualizado no Brew, mas no PATH estava configurado pra usar o Node do NVM. Detectei o problema, e fiz as atualizações que precisava. Mas...

![screenshot 2015-10-28 18 07 48](https://cloud.githubusercontent.com/assets/5032844/10801556/15fea8a8-7d9f-11e5-935d-46c9b53fd940.png)

**Comment by brenoc** [comment]
Tava escrevendo agora pra vc atualizar a versão do node haha droga

@tamorim alguma ideia?

**Comment by tamorim** [comment]
Pode botar o resultado de dois comandos aqui?
Um é o `npm ls -g --depth=0` e o outro é o `npm ls --depth=0`

**Comment by josantana** [comment]
```
▸ npm ls -g --depth=0
/usr/local/lib
├── bower@1.4.1
├── browser-sync@1.5.8
├── coffeelint@1.10.1
├── csslint@0.10.0
├── express@4.10.2
├── express-generator@4.9.0
├── generator-chrome-extension@0.2.11
├── generator-express@2.3.0
├── generator-mocha@0.1.6
├── generator-vtex@1.4.6
├── grunt-cli@0.1.13
├── gulp@3.9.0
├── jshint@2.6.3
├── jsxhint@0.15.1
├── localtunnel@1.4.0
├── nave@0.4.5
├── node-gyp@1.0.2
├── npm@2.14.7
├── polyserve@0.4.0
├── typescript@1.5.3
├── vtex@0.10.1
└── yo@1.4.8
```

```
▸ npm ls --depth=0
storefront-theme@ /Users/Shared/Git/web/user-interface/polishop/storefront-default
├── babel-core@5.8.30
├── babel-eslint@3.1.30
├── babel-loader@5.3.2
├── babel-plugin-react-transform@1.1.1
├── bootstrap@3.3.5
├── colr@1.2.2
├── css-loader@0.9.1
├── eslint@1.7.3
├── eslint-config-vtex@1.0.0
├── eslint-loader@1.1.0
├── eslint-plugin-react@3.6.3
├── express@4.13.3
├── file-loader@0.8.4
├── http-proxy@1.12.0
├── less@2.5.3
├── less-loader@2.2.1
├── loader-utils@0.2.11
├── lodash-compat@3.10.1
├── minimist@1.2.0
├── node-sass@3.4.1
├── raw-loader@0.5.1
├── react@0.14.0
├── react-colorpicker@0.3.14
├── react-dragula@1.1.3
├── react-proxy-loader@0.3.4
├── react-transform-catch-errors@1.0.0
├── react-transform-hmr@1.0.1
├── redbox-react@1.1.1
├── sass-loader@3.1.1
├── style-loader@0.9.0
├── svgo@0.5.6
├── svgo-loader@1.1.0
├── url-loader@0.5.6
├── webpack@1.12.2
└── webpack-hot-middleware@2.4.1
```

**Comment by tamorim** [comment]
Achei que poderia ter um conflito de toolbelts instalados, mas pelo visto está tudo ok.
Vou lançar um patch agora, com umas alterações que o @brenoc fez, de repente nos ajude a debugar melhor!

**Comment by tamorim** [comment]
Lancei agora a versão 0.10.2, atualiza aí e vê se dá o mesmo erro, por favor :)

**Comment by josantana** [comment]
@tamorim Continua retornando `null`, porém, durante a instalação apareceram alguns erros.

```
▸ npm i -g vtex
-
> websocket@1.0.22 install /usr/local/lib/node_modules/vtex/node_modules/signalr-client/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> fsevents@1.0.2 install /usr/local/lib/node_modules/vtex/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp: /Users/polishop/.node-gyp/4.2.1/common.gypi not found (cwd: /usr/local/lib/node_modules/vtex/node_modules/chokidar/node_modules/fsevents) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/vtex/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" "--module_name=fse" "--module_path=/usr/local/lib/node_modules/vtex/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64" "--python=/usr/bin/python"
gyp ERR! cwd /usr/local/lib/node_modules/vtex/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/vtex/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/vtex/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64 --python=/usr/bin/python' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/vtex/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.0.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/vtex/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/vtex/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v4.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.12
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/vtex/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/vtex/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64 --python=/usr/bin/python' (1)
npm WARN optional dep failed, continuing fsevents@1.0.2
/usr/local/bin/vtex -> /usr/local/lib/node_modules/vtex/lib/vtex.js
/usr/local/bin/vtex-login -> /usr/local/lib/node_modules/vtex/lib/vtex-login.js
/usr/local/bin/vtex-logout -> /usr/local/lib/node_modules/vtex/lib/vtex-logout.js
/usr/local/bin/vtex-watch -> /usr/local/lib/node_modules/vtex/lib/vtex-watch.js
/usr/local/bin/vtex-publish -> /usr/local/lib/node_modules/vtex/lib/vtex-publish.js
vtex@0.10.2 /usr/local/lib/node_modules/vtex
├── q@1.4.1
├── docopt@0.6.2
├── semver@5.0.3
├── supports-color@3.1.2 (has-flag@1.0.0)
├── webpack-dev-middleware@1.2.0 (memory-fs@0.2.0, mime@1.3.4)
├── http-proxy@1.12.0 (eventemitter3@1.1.1, requires-port@0.0.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── shelljs@0.5.3
├── webpack-hot-middleware@2.4.1 (querystring@0.2.0, strip-ansi@2.0.1)
├── vtexsay@1.0.3 (ansi-styles@2.1.0, ansi-regex@1.1.1, word-wrap@1.1.0, strip-ansi@2.0.1, pad-component@0.0.1, taketalk@1.0.0, minimist@1.2.0, string-length@1.0.1)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@3.0.0)
├── express@4.13.3 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.1, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, content-type@1.0.1, vary@1.0.1, methods@1.1.1, path-to-regexp@0.1.7, fresh@0.3.0, range-parser@1.0.2, etag@1.7.0, content-disposition@0.5.0, serve-static@1.10.0, parseurl@1.3.0, depd@1.0.1, qs@4.0.0, on-finished@2.3.0, finalhandler@0.4.0, debug@2.2.0, proxy-addr@1.0.8, accepts@1.2.13, type-is@1.6.9, send@0.13.0)
├── tiny-lr@0.2.1 (parseurl@1.3.0, livereload-js@2.2.2, qs@5.1.0, debug@2.2.0, body-parser@1.14.1, faye-websocket@0.10.0)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.1, read@1.0.7, winston@0.8.3, utile@0.2.1)
├── request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.1, oauth-sign@0.8.0, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.0, node-uuid@1.4.3, qs@5.2.0, combined-stream@1.0.5, mime-types@2.1.7, form-data@1.0.0-rc3, http-signature@0.11.0, hawk@3.1.0, bl@1.0.0, har-validator@2.0.2)
├── node-libs-browser@0.5.3 (https-browserify@0.0.0, tty-browserify@0.0.0, path-browserify@0.0.0, constants-browserify@0.0.1, punycode@1.3.2, string_decoder@0.10.31, os-browserify@0.1.2, process@0.11.2, domain-browser@1.1.4, assert@1.3.0, querystring-es3@0.2.1, timers-browserify@1.4.1, events@1.1.0, stream-browserify@1.0.0, vm-browserify@0.0.4, readable-stream@1.1.13, util@0.10.3, url@0.10.3, console-browserify@1.1.0, http-browserify@1.7.0, buffer@3.5.1, browserify-zlib@0.1.4, crypto-browserify@3.2.8)
├── archiver@0.15.1 (async@1.4.2, buffer-crc32@0.2.5, lazystream@0.1.0, readable-stream@1.0.33, tar-stream@1.2.2, zip-stream@0.5.2, lodash@3.10.1)
├── webpack@1.12.2 (interpret@0.6.6, tapable@0.1.9, async@1.5.0, memory-fs@0.2.0, clone@1.0.2, esprima@2.7.0, mkdirp@0.5.1, enhanced-resolve@0.9.1, watchpack@0.2.9, optimist@0.6.1, webpack-core@0.6.7, uglify-js@2.4.24)
├── signalr-client@0.0.16 (websocket@1.0.22)
└── chokidar@1.2.0 (arrify@1.0.0, path-is-absolute@1.0.0, async-each@0.1.6, glob-parent@2.0.0, is-glob@2.0.1, is-binary-path@1.0.1, lodash.flatten@3.0.2, readdirp@2.0.0, anymatch@1.3.0)
```

**Comment by tamorim** [comment]
Creio ter descoberto o que era.

Quando você não tem um workspace no novo modelo `sb_<seu-email>` o servidor me retorna um 201, e no array de statusCodes aceitáveis ele não tava presente.

O estranho é: seria 'comum' acontecer na primeira vez, nas vezes subsequentes o workspace já estaria criado e teria o curso normal.

Vou subir um patch e por favor me avisa se resolve o bug!

**Comment by josantana** [comment]
Continua dando erro na hora de instalar o `vtex` aqui, mas instala. Mas ao dar `watch`, ainda retorna `null`.

Dei uninstall, instalei de novo, desloguei e loguei de novo várias vezes... nada.

**Comment by tamorim** [comment]
@josantana @brenoc 
Nos ajudou a achar outro bug, apesar de não ter sido esse o caso haha
Vou fechar essa issue, ok? :)
