### ISSUE TITLE
Release command with help flag proceeds to release normally

### ISSUE THREAD

**Issue by lucasecdb** [vtex/toolbelt#749]
## Expected Behavior
I expected that `vtex release --help` would show a brief summary of how this command works (e.g. which flags can I pass to it).

## Current Behavior
Currently, when you run `vtex release --help` it still goes through the normal release 

## Steps to Reproduce (for bugs)

1. Run `vtex release --help`

## Context
I'm trying to see how can I publish a stable version. Running `vtex release minor --stable` still proceeds to release a beta version. I also tried `vtex release --stable minor`, but this way it tries to publish a beta patch (?).

## Your Environment

* Version used: 2.88.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): node v13.7.0
* Operating System and version (desktop or mobile): macOS

**Comment by lucasecdb** [comment]
I also found out that if you run the release without a valid "release type" it throws an error

```
10:19:28.551 - error: Invalid release type: stable-minor
Valid release types are: major, minor, patch, prerelease
10:19:28.553 - error: Unhandled exception
10:19:28.553 - error: Please report the issue in https://github.com/vtex/toolbelt/issues
10:19:28.554 - error: Raw error:Invalid release type: stable-minor
Valid release types are: major, minor, patch, prerelease Error: Invalid release type: stable-minor
Valid release types are: major, minor, patch, prerelease
    at getNewAndOldVersions (/Users/lucascordeiro/.config/yarn/global/node_modules/vtex/lib/modules/release/index.js:44:19)
    at Object.exports.default (/Users/lucascordeiro/.config/yarn/global/node_modules/vtex/lib/modules/release/index.js:65:38)
    at Object.run (/Users/lucascordeiro/.config/yarn/global/node_modules/findhelp/lib/finder.js:180:18)
    at run (/Users/lucascordeiro/.config/yarn/global/node_modules/vtex/lib/cli.js:33:55)
    at main (/Users/lucascordeiro/.config/yarn/global/node_modules/vtex/lib/cli.js:63:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by tiagonapoli** [comment]
Unfortunately in the current CLI Framework no --help flags, only when running `vtex --help`.

I'm migrating the CLI to [oclif](https://oclif.io/), then we will not have this problem anymore
