### ISSUE TITLE
Cannot generate typings URL for package vtex.checkout-resources

### ISSUE THREAD

**Issue by lucasecdb** [vtex/toolbelt#764]
## Current Behavior
I'm executing `vtex setup` inside an app that depends on the `vtex.checkout-resources` app.

I recently released a version for it (which is the one that toolbelt started not being able to generate the URL) which changed the files from `.js` extension to `.tsx`. The PR is vtex-apps/checkout-resources#27

## Expected Behavior
The expected behavior is to generate the typings URL and update the `package.json` without error.

## Possible Solution
I don't know :-/

## Steps to Reproduce (for bugs)

1. Clone [vtex-apps/order-profile](https://github.com/vtex-apps/order-profile).
2. Add the `vtex.checkout-resources` dependency.
3. Run `vtex setup`.

## Context
I'm trying to get the latest typings for the app version.

## Your Environment

* Version used: 2.90.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js 13.7.0
* Operating System and version (desktop or mobile): macOS 10.15
* Link to your project: [vtex-apps/order-profile](https://github.com/vtex-apps/order-profile).

**Comment by lucasecdb** [comment]
I added a log to the error in the `checkIfTarGzIsEmpty` function and here is what I'm getting:

```ZlibError: zlib: unexpected end of file
    at Unzip.Zlib.<computed> (/Users/lucascordeiro/sources/vtex/toolbelt/node_modules/minizlib/index.js:126:21)
    at Unzip.write (/Users/lucascordeiro/sources/vtex/toolbelt/node_modules/minizlib/index.js:247:21)
    at Unzip.flush (/Users/lucascordeiro/sources/vtex/toolbelt/node_modules/minizlib/index.js:206:10)
    at Unzip.end (/Users/lucascordeiro/sources/vtex/toolbelt/node_modules/minizlib/index.js:213:10)
    at Object.end (/Users/lucascordeiro/sources/vtex/toolbelt/node_modules/tar/lib/parse.js:421:21)
    at IncomingMessage.onend (_stream_readable.js:673:10)
    at Object.onceWrapper (events.js:427:28)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
```

**Comment by tiagonapoli** [comment]
This is a known bug that we are facing for some months already. We don't know the reason yet - sometimes assets are cached in an invalid state, or router responses are incomplete. Unfortunately now I can't do much to fix this
