### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by mgvarela** [vtex/toolbelt#982]
## Expected Behavior
i want to log into my account from console terminal

## Current Behavior
I can't start the section, because "vtex login acount" returns the following error

## Steps to Reproduce (for bugs)

5:31:37.580 - error: Unhandled exception  
15:31:37.580 - error: Please report the issue in https://github.com/vtex/toolbelt/issues  
15:31:37.581 - error: Raw error: Error trying to call client before login. Error: Error trying to call client before login.
    at Proxy.<anonymous> (/home/corebiz/.config/yarn/global/node_modules/vtex/lib/api/clients/IOClients/IOClientFactory.js:53:27)
    at OAuthAuthenticator.login (/home/corebiz/.config/yarn/global/node_modules/vtex/lib/lib/auth/AuthProviders/OAuthAuthenticator/index.js:38:57)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async SessionManager.login (/home/corebiz/.config/yarn/global/node_modules/vtex/lib/api/session/SessionManager.js:81:31)
    at async Object.exports.default (/home/corebiz/.config/yarn/global/node_modules/vtex/lib/modules/auth/login.js:77:9)
    at async Login.run (/home/corebiz/.config/yarn/global/node_modules/vtex/lib/commands/login.js:10:9)
    at async Login._run (/home/corebiz/.config/yarn/global/node_modules/vtex/lib/api/oclif/CustomCommand.js:25:28)
    at async Config.ctx.config.runCommand (/home/corebiz/.config/yarn/global/node_modules/@tiagonapoli/oclif-plugin-spaced-commands/lib/hooks/init.js:89:9)
    at async Main.run (/home/corebiz/.config/yarn/global/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/home/corebiz/.config/yarn/global/node_modules/@oclif/command/lib/command.js:43:20)  
15:31:37.583 - error: ErrorID: 0a043eb729bcdf3e000ae0962350e617 

## Context
I can't start section to develop

## Your Environment

* Version used: vtex/2.118.0 
* Environment name and version (e.g. Chrome 39, node.js 5.4): linux-x64 node-v12.18.3
* Operating System and version (desktop or mobile): Linux 18.01 desktop 
* Link to your project: https://github.com/corebiz-global/weloveshoescl

**Comment by alejomoreno07** [comment]
Could you try installing vtex@2.110.2-beta.0 ?? It worked for me.

**Comment by mgvarela** [comment]
yes thanks, may need to install new version of node?

**Comment by alejomoreno07** [comment]
it would be better if you use Can you try node@12.x instead of node@13.x . Anyway, I'm glad to help

**Comment by alejomoreno07** [comment]
it would be better if you use node@12.x instead of node@13.x . Anyway, I'm glad to help

**Comment by alektobias** [comment]
Same here! I'm using node 12 and Vtex 2.122.1
